import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route } from "react-router-dom";
import Signup from "../../pages/Signup";
// import VerifyOTP from "../../pages/VerifyOTP";
import Login from "../Login";
import AdminLogin from "../AdminLogin";
// import Dashboard from "./components/Dashboard";
import "react-toastify/dist/ReactToastify.css";
// import Home from "./components/Home";
import ProtectedRoute from "../ProtectedRoute";
import AdminDashboard from "../../pages/AdminDashboard";
// import CustomerDashboard from "./components/admin/dashboard/CustomerDashboard";
import AdminCustomers from "../../pages/AdminCustomers";
// import Plans from './components/admin/plans/Plans'
// import AddPlansPage from "./components/admin/plans/AddPlan";
import AdminPlans from "../../pages/AdminPlans";
import AdminAddPlan from "../../pages/AdminAddPlans";
import AdminEditPlan from "../../pages/AdminEditPlan";
// import Header from "./components/User/Header/Header";
import HomePage from "../User/Header/HomePage";
import LandingPage from "../../pages/LandingPage";
import ProfilePage from "../User/Profile/Page";
// import ListRoom from "./components/User/Room/ListRoom";
// import RoomPage from "../User/Room/AddRoomPage";
// import AddRoom from "./components/User/Room/AddRoom";
import AddRoomPage from "../User/Room/AddRoomPage";
import RoomPage from "../User/Room/RoomPage";
import RoomCall from "../User/Room/Calls/RoomCall";
// import FriendRequests from "../User/Friends/FriendRequest";
import AdminRoom from "@/pages/AdminRoom";
// import UserTrivia from "../User/Trivia/UserTrivia";
import TriviaPage from "../User/Trivia/TriviaPage";
import AdminTriviaPage from "@/pages/AdminTririvaPage";
import AdminTriviaAddPage from "@/pages/AdminTriviaAdd";
import AdminEditTriviaPage from "@/pages/AdminTriviaEdit";
import ChatDashboard from "../User/Chat/ChatDashboard";
import AdminRewardPage from "../admin/Reward/RewardPage";
import AddRewardPage from "../admin/Reward/AddRewardPage";
import RoomDetailsPage from "../admin/Room/RoomDetailsPage";
import RewardPage from "../User/Reward/RewardPage";
import PlansPage from "../User/Plans/PlansPage";
import PricingSuccess from "../User/Plans/PricingSuccess";
import UserProtectedRoute from "../User/UserProtectedRoute";
import DirectCallPage from "../User/Chat/DirectCallPage";
// import AdminDashboardd from "../admin/Dashboardd/AdminDashboard";
import DashboardPageAdmin from "@/pages/DashboardPage";
// import CreatePost from "../User/Post/CreatePost";
// import MyPosts from "../User/Post/MyPost";
// import PostFeed from "../User/Post/PostFeed";
import MyPostPage from "../User/Post/MyPostPage";
import PostView from "../User/Post/PostView";
import FeedPage from "../User/Post/FeedPage";
import FriendRequestPage from "../User/Friends/FriendRequestPage";
function AppRoute() {
    return (_jsxs(Routes, { children: [_jsx(Route, { path: "/signup", element: _jsx(Signup, {}) }), _jsx(Route, { path: "/landing", element: _jsx(LandingPage, {}) }), _jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/adminLogin", element: _jsx(AdminLogin, {}) }), _jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsxs(Route, { element: _jsx(UserProtectedRoute, {}), children: [_jsx(Route, { path: "/friends/request", element: _jsx(FriendRequestPage, {}) }), _jsx(Route, { path: "/room/:roomId/call", element: _jsx(RoomCall, {}) }), _jsx(Route, { path: "/profile", element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: "/addRoom", element: _jsx(AddRoomPage, {}) }), _jsx(Route, { path: "/rooms", element: _jsx(RoomPage, {}) }), _jsx(Route, { path: "/dailyTrivia", element: _jsx(TriviaPage, {}) }), _jsx(Route, { path: "/friends", element: _jsx(ChatDashboard, {}) }), _jsx(Route, { path: "/rewards", element: _jsx(RewardPage, {}) }), _jsx(Route, { path: "/user/plans", element: _jsx(PlansPage, {}) }), _jsx(Route, { path: "/pricing/success", element: _jsx(PricingSuccess, {}) }), _jsx(Route, { path: "/call/:callId", element: _jsx(DirectCallPage, {}) }), _jsx(Route, { path: "/myPost", element: _jsx(MyPostPage, {}) }), _jsx(Route, { path: "/feed", element: _jsx(FeedPage, {}) }), _jsx(Route, { path: "/post/:postId", element: _jsx(PostView, {}) })] }), _jsxs(Route, { element: _jsx(ProtectedRoute, {}), children: [_jsx(Route, { path: "/dashboard", element: _jsx(AdminDashboard, {}) }), _jsx(Route, { path: "/plans", element: _jsx(AdminPlans, {}) }), _jsx(Route, { path: "/users", element: _jsx(AdminCustomers, {}) }), _jsx(Route, { path: "/plans/edit/:id", element: _jsx(AdminEditPlan, {}) }), _jsx(Route, { path: "/plans/add", element: _jsx(AdminAddPlan, {}) }), _jsx(Route, { path: "/admin/rooms", element: _jsx(AdminRoom, {}) }), _jsx(Route, { path: "/trivia/add", element: _jsx(AdminTriviaAddPage, {}) }), _jsx(Route, { path: "/trivia", element: _jsx(AdminTriviaPage, {}) }), _jsx(Route, { path: "/admin/trivia/edit/:id", element: _jsx(AdminEditTriviaPage, {}) }), _jsx(Route, { path: "/admin/room-details/:id", element: _jsx(RoomDetailsPage, {}) }), _jsx(Route, { path: "/admin/rewards", element: _jsx(AdminRewardPage, {}) }), _jsx(Route, { path: "/admin/rewards/add", element: _jsx(AddRewardPage, {}) }), _jsx(Route, { path: "/admin/rewards/edit/:rewardId", element: _jsx(AddRewardPage, {}) }), _jsx(Route, { path: "/dashboardPage", element: _jsx(DashboardPageAdmin, {}) })] })] }));
}
export default AppRoute;
